env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - git clone https://github.com/wbhart/bsdnt.git bsdnt-git
  - cd bsdnt-git
  - ./configure
  - make
  - sudo make install
  - cd ..
script:
  - cargo build
  - cargo test
  - cargo test -- --bench
