before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - git clone https://github.com/wbhart/bsdnt.git bsdnt-git
  - cd bsdnt-git
  - git checkout origin/v1.0
  - ./configure
  - make
  - cd ..
script:
  - rustc bsdnt.rs --test -L bsdnt-git
  - RUST_THREADS=1 LD_LIBRARY_PATH=bsdnt-git ./bsdnt --test
